-- Supabase Database Schema for AZYMAR

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- =============================================================================
-- 1. GAMES TABLE
-- =============================================================================
create table if not exists public.games (
    id bigint generated by default as identity primary key,
    title text not null,
    genre text not null,
    rating numeric not null default 0.0,
    plays text not null default '0',
    badge text check (badge in ('HOT', 'NEW', 'TRENDING')),
    color text not null default '#11B5A4',
    emoji text not null default '🎮',
    is_uploaded boolean not null default false,
    zip_url text,
    visible boolean not null default true,
    uploaded_at timestamp with time zone not null default now(),
    size text
);

-- Enable Row Level Security (RLS)
alter table public.games enable row level security;

-- Policies for public.games
create policy "Allow public read access to games"
    on public.games for select
    using (true);

create policy "Allow public insert access to games"
    on public.games for insert
    with check (true);

create policy "Allow public update access to games"
    on public.games for update
    using (true);

create policy "Allow public delete access to games"
    on public.games for delete
    using (true);

-- =============================================================================
-- 2. SUBSCRIBERS TABLE
-- =============================================================================
create table if not exists public.subscribers (
    id uuid default gen_random_uuid() primary key,
    email text unique not null,
    created_at timestamp with time zone not null default now()
);

-- Enable RLS
alter table public.subscribers enable row level security;

-- Policies for public.subscribers
create policy "Allow public insert to newsletter"
    on public.subscribers for insert
    with check (true);

create policy "Allow authenticated read to newsletter"
    on public.subscribers for select
    to authenticated
    using (true);

-- =============================================================================
-- 3. FAVORITES TABLE
-- =============================================================================
create table if not exists public.favorites (
    id uuid default gen_random_uuid() primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    game_id bigint not null references public.games(id) on delete cascade,
    created_at timestamp with time zone not null default now(),
    unique(user_id, game_id)
);

-- Enable RLS
alter table public.favorites enable row level security;

-- Policies for public.favorites
create policy "Allow users to view their own favorites"
    on public.favorites for select
    using (auth.uid() = user_id);

create policy "Allow users to insert their own favorites"
    on public.favorites for insert
    with check (auth.uid() = user_id);

create policy "Allow users to delete their own favorites"
    on public.favorites for delete
    using (auth.uid() = user_id);

-- =============================================================================
-- 4. PLAY HISTORY / RECOMMENDED PROGRESS TABLE
-- =============================================================================
create table if not exists public.play_history (
    id uuid default gen_random_uuid() primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    game_id bigint not null references public.games(id) on delete cascade,
    progress integer not null default 0 check (progress >= 0 and progress <= 100),
    updated_at timestamp with time zone not null default now(),
    unique(user_id, game_id)
);

-- Enable RLS
alter table public.play_history enable row level security;

-- Policies for public.play_history
create policy "Allow users to view their own play history"
    on public.play_history for select
    using (auth.uid() = user_id);

create policy "Allow users to insert/update their own play history"
    on public.play_history for insert
    with check (auth.uid() = user_id);

create policy "Allow users to update their own play history"
    on public.play_history for update
    using (auth.uid() = user_id);
